name: eeg-bci-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mne
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip
  - imbalanced-learn
  - pip:
      - torch
      - torchvision
